spring:
  datasource:
    #    url: jdbc:postgresql://localhost:5432/bookrental
    #    username: postgres
    #    password: prabin
    url: jdbc:postgresql://dpg-cmme4q21hbls73cfe450-a.singapore-postgres.render.com/bookrental
    username: bookrental_user
    password: kw0Wiol8rH75IBdYCFSe8BAdzI9mbNqj
    driver-class-name: org.postgresql.Driver
  #testing
  #testing

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      format_sql: true
    open-in-view: false

#  profiles:
#    active: ${ENV:dev}

server:
  port: 9889
  servlet:
    context-path: /book-rental


#security:
#  user:
#    name: prabin
#    password: prabin

#springdoc:
#  swagger-ui:
#    urls:
#      - url: "/book-rental/v3/api-docs"
#        name: "book-rental"
#    enabled: true
#    path: /swagger-ui.html
#  api-docs:
#    path: /v3/api-docs
#    version: openapi_3_1
#    enabled: true
