spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookrental
    username: postgres
    password: prabin
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      format_sql: true
    open-in-view: false

server:
  port: 9889
  servlet:
    context-path: /book-rental

security:
  user:
    name: prabin
    password: prabin

springdoc:
  swagger-ui:
    urls:
      - url: "/book-rental/api-docs"
        name: "book-rental"
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
    version: openapi_3_1
