spring:
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:27072/railway
    username: postgres
    password: 3FB*ae4Ea6cc2cBgFef14g6FfA*d*42*
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      format_sql: true
    open-in-view: false

server:
  port: 9889
  servlet:
    context-path: /book-rental


